package dailyquest.achievement.entity

enum class AchievementType {
    QUEST_REGISTRATION, QUEST_COMPLETION, QUEST_CONTINUOUS_REGISTRATION_DAYS,
    QUEST_CONTINUOUS_COMPLETION,
    USER_LEVEL, GOLD_EARN,
    EMPTY
}