quest:
  page:
    size: 20

notification:
  page:
    size: 10

security:
  url:
    allowed_url: ["/", "/css/**", "/js/**", "/image/**", "/error", "/api/v1/auth/**"]
    admin_url: ["/admin/**"]
  origin:
    allowed_origin: ["http://localhost:9090", "https://dailyquest.mooo.com", "http://localhost:9080"]

spring:
  jwt:
    secret: ${JWT_SECRET}

google:
  client-id: ${GOOGLE_CLIENT_ID}

redis:
  key:
    exp_table: ${REDIS_EXP_TABLE_KEY}
    nickname_prefix: ${REDIS_NICKNAME_PREFIX_KEY}
    nickname_postfix: ${REDIS_NICKNAME_POSTFIX_KEY}
    settings: ${REDIS_SETTINGS_KEY}
    quest_clear_exp: ${REDIS_QUEST_CLEAR_EXP_KEY}
    quest_clear_gold: ${REDIS_QUEST_CLEAR_GOLD_KEY}
    max_reward_count: ${REDIS_MAX_REWARD_COUNT_KEY}

elastic:
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  host: ${ELASTIC_HOST}
  port: ${ELASTIC_PORT}

jwt:
  access-token-expiration-seconds-formula: ${ACCESS_TOKEN_EXPIRATION_SECONDS_FORMULA}
  refresh-token-expiration-seconds-formula: ${REFRESH_TOKEN_EXPIRATION_SECONDS_FORMULA}
  access_token_name: ${ACCESS_TOKEN_NAME}
  refresh_token_name: ${REFRESH_TOKEN_NAME}
  use_secure: ${TOKEN_USE_SECURE:true}
  same_site: ${TOKEN_SAME_SITE_STRATEGY:strict}
  domain: ${TOKEN_DOMAIN}

http:
  response:
    date-format: ${HTTP_RESPONSE_DATE_FORMAT:yyyy-MM-dd}
    time-format: ${HTTP_RESPONSE_TIME_FORMAT:HH:mm:ss}
    date-time-format: ${HTTP_RESPONSE_DATE_TIME_FORMAT:yyyy-MM-dd HH:mm:ss}
aws:
  sqs:
    queue:
      batch-job-queue-url: ${AWS_SQS_BATCH_JOB_QUEUE_URL}
      elastic-sync-queue-url: ${AWS_SQS_ELASTIC_SYNC_QUEUE_URL}