#!/bin/bash

redis-cli select 1

redis-cli SADD REDIS_NICKNAME_PREFIX_KEY pre1
redis-cli SADD REDIS_NICKNAME_PREFIX_KEY pre2
redis-cli SADD REDIS_NICKNAME_PREFIX_KEY pre3

redis-cli SADD REDIS_NICKNAME_POSTFIX_KEY post1
redis-cli SADD REDIS_NICKNAME_POSTFIX_KEY post2
redis-cli SADD REDIS_NICKNAME_POSTFIX_KEY post3

redis-cli HSET REDIS_EXP_TABLE_KEY 1 10
redis-cli HSET REDIS_EXP_TABLE_KEY 2 20
redis-cli HSET REDIS_EXP_TABLE_KEY 3 30
redis-cli HSET REDIS_EXP_TABLE_KEY 4 0

redis-cli HSET REDIS_SYSTEM_SETTINGS_KEY REDIS_QUEST_CLEAR_EXP_KEY 1
redis-cli HSET REDIS_SYSTEM_SETTINGS_KEY REDIS_QUEST_CLEAR_GOLD_KEY 1
redis-cli HSET REDIS_SYSTEM_SETTINGS_KEY REDIS_MAX_REWARD_COUNT_KEY 30